from .endpoints import (AutomationEndpoints,
                        CustomFieldEndpoints,
                        DeleteExecutionEndpoints,
                        EnvironmentEndpoints,
                        FolderEndpoints,
                        IssueLinkEndpoints,
                        ProjectEndpoints,
                        TestCaseEndpoints,
                        TestPlanEndpoints,
                        TestResultEndpoints,
                        TestRunEndpoints)
