from .environments import EnvironmentEndpoints
from .test_cases import TestCaseEndpoints
from .projects import ProjectEndpoints
from .test_cycles import TestCycleEndpoints
from .test_plans import TestPlanEndpoints
from .test_executions import TestExecutionEndpoints
from .folders import FolderEndpoints
from .statuses import StatusEndpoints
from .priorities import PriorityEndpoints
