from .endpoints import (TestCaseEndpoints,
                        TestCycleEndpoints,
                        TestPlanEndpoints,
                        TestExecutionEndpoints,
                        FolderEndpoints,
                        StatusEndpoints,
                        PriorityEndpoints,
                        EnvironmentEndpoints,
                        ProjectEndpoints,
                        LinkEndpoints,
                        IssueLinksEndpoints,
                        AutomationEndpoints,
                        HealthcheckEndpoints)
